name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
   using: "docker"
   image: "Dockerfile"
branding: 
   icon: "git-branch"
   color: "red"
input:
   email:
     description: The commiter's email adderess
     required: true
     

   name:
     description: The commiter's name
     required: true
     
